name: Gerar relatório financeiro

on:
  push:
    paths:
      - 'movimentos*.csv'
      - 'relatorio_financeiro.py'

jobs:
  gerar-financeiro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install pandas

      - name: Executar script financeiro
        id: gerar
        run: |
          python relatorio_financeiro.py > output.txt
          # apanhar o nome do ficheiro criado, última linha do print
          RELATORIO=$(grep "Relatório gerado:" output.txt | awk '{print $3}')
          echo "RELATORIO=$RELATORIO" >> $GITHUB_ENV

      - name: Guardar relatório como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELATORIO }}
          path: ${{ env.RELATORIO }}
